name: Build Release APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    environment: telegram-foss
    env:
      ANDROID_NDK_URL: https://dl.google.com/android/repository/android-ndk-r21e-linux-x86_64.zip
      ANDROID_NDK_HOME: /usr/local/lib/android/sdk/ndk/21.4.7075529
      NDK: /usr/local/lib/android/sdk/ndk/21.4.7075529
      NINJA_PATH: /usr/bin/ninja
    steps:
    - uses: actions/cache@v4
      id: cache-ndk
      with:
        path: ${{ env.ANDROID_NDK_HOME }}
        key: android-ndk-r21e-linux-x86_64

    - name: Download Android NDK
      if: steps.cache-ndk.outputs.cache-hit != 'true'
      run: |
        curl -o ndk.zip "$ANDROID_NDK_URL"
        unzip -q ndk.zip
        mv android-ndk-r21e "$ANDROID_NDK_HOME"

    - name: Install packages
      env:
        DEBIAN_FRONTEND: noninteractive
      run: sudo apt install -y libuv1 ninja-build yasm patch

    - uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '11'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3
      with:
        gradle-version: 7.2

    - uses: actions/checkout@v4
      with:
        submodules: true

    - name: Compile JNI libraries
      run: |
        pushd TMessagesProj/jni
        ./build_libvpx_clang.sh
        ./build_ffmpeg_clang.sh
        ./patch_ffmpeg.sh
        ./patch_boringssl.sh
        ./build_boringssl.sh
        popd

    - name: Build APK
      env:
        API_KEYS: ${{ secrets.API_KEYS }}
      run: |
        printf "$API_KEYS" > API_KEYS
        ./gradlew :TMessagesProj_App:assembleAfatRelease
        find TMessagesProj_App/build -name '*.apk'
