name: Build Release APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ANDROID_NDK_URL: https://dl.google.com/android/repository/android-ndk-r21e-linux-x86_64.zip
      ANDROID_NDK_HOME: /usr/local/lib/android/sdk/ndk/21.4.7075529
      NDK: /usr/local/lib/android/sdk/ndk/21.4.7075529
      NINJA_PATH: /usr/bin/ninja
    steps:
    - name: Setup Android NDK
      run: |
        mkdir -p cache
        if [ ! -f cache/ndk.zip ]; then
          curl -o cache/ndk.zip "$ANDROID_NDK_URL"
        fi
        unzip -q cache/ndk.zip
        mv android-ndk-*/ "$ANDROID_NDK_HOME"

    - name: Install packages
      env:
        DEBIAN_FRONTEND: noninteractive
      run: sudo apt install -y libuv1 ninja-build yasm patch

    - name: Setup Gradle
      uses: gradle/gradle-build-action@v3
      with:
        gradle-version: 7.2

    - uses: actions/checkout@v4
      with:
        submodules: true

    - name: Compile JNI libraries
      run: |
        cd TMessagesProj/jni
        ./build_libvpx_clang.sh
        ./build_ffmpeg_clang.sh
        ./patch_ffmpeg.sh
        ./patch_boringssl.sh
        ./build_boringssl.sh

    - name: Build APK
      run: |
        ./gradlew :TMessagesProj_App:assembleAfatRelease
        ls -l TMessagesProj_App/app/build/outputs
